### ISSUE TITLE
adding command names as things borks sk

### ISSUE THREAD

**Issue by actowery** [LouisSavoie/simple-karma#7] opened 2021-04-27 01:49 UTC
```
sk +karma +karma
SimpleKarma
BOT
 — Today at 9:46 PM
+karma has 1 karma.
sk +karma
sk new +karma
sk new -karma
sk new delete
sk new lol?
borked
```

**Comment by LouisSavoie** [comment] 2021-04-28 01:39
I am currently overhauling most of the functions in SK, so I will attempt to replicate this afterwards in case it is fixed in the process as a side effect. Thanks for the report, hold tight :D

**Comment by LouisSavoie** [comment] 2021-05-02 23:18
Testing this after the overhaul I am able to replicate crashing the bot with the command `sk +` which is the new equivalent to the command `sk +karma` that you used. This is the command to increment the karma of a 'thing' but leaving the 'thing' as undefined.

Here is the console information I got with `sk +`:
```
2021-05-02T23:08:30.317362+00:00 app[worker.1]: ================= Command Args ==================
2021-05-02T23:08:30.317456+00:00 app[worker.1]: DEBUG: command: +
2021-05-02T23:08:30.317492+00:00 app[worker.1]: DEBUG: thingName: undefined
2021-05-02T23:08:30.317550+00:00 app[worker.1]: DEBUG: getThingName: +
2021-05-02T23:08:30.317616+00:00 app[worker.1]: DEBUG: getThingNameCharCodes: 43
2021-05-02T23:08:30.320198+00:00 app[worker.1]: (node:21) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'includes' of undefined
2021-05-02T23:08:30.320199+00:00 app[worker.1]:     at Object.execute (/app/commands/incrementKarma.js:10:24)
```

The issue is that in the incrementKarma command file the String method `.includes` is called on the variable `thingName`, which you can see in the log is undefined as it was not given in the Discord message.

I will update when I have found a fix, which should be as simple as checking for undefined, but I want to take this opportunity to also create a Discord reply to inform the user of this behavior.

**Closed** 2021-05-03 02:21 UTC
